<a href="https://colab.research.google.com/github/bmassuco/Ingenias_DS/blob/main/Copia_de_N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
# Importamos la biblioteca Numpy
import numpy as np

In [ ]:
# Ejericio 1
# Crear un arreglo de ceros de longitud 12
ej1 = np.zeros(12)
print(ej1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2
# Crea un arrelgo de longitud 10 con ceros en todas las posiciones y un 10 en la posicion numero 5
ej2 = np.zeros(10)
ej2[4] = 10
print(ej2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
# Ejercicio 3
# Crear un arreglo que tenga los números del 10 al 49

arreglo3 = np.arange(10,50)
print(arreglo3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Ejercicio 3
# Crear un arreglo que tenga los números del 10 al 49

ej3 = np.arange(10,49)
print(ej3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
# Ejercicio 4
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
ej4 = np.arange(9).reshape(3,3)
print(ej4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Ejercicio 5
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.
print("creacion de longuitud aleatorio de 100 ")
arreglo5 = np.random.randn(100)
print(arreglo5)
print ()
print("creacion de media ")
media = np.mean(arreglo5)
print(media)
print()
print("creacion de varianza ")
varianza = np.var(arreglo5)
print(varianza)

creacion de longuitud aleatorio de 100 
[-2.50085116  0.13026253  0.01022451 -0.06586791 -1.9935581  -0.71871526
 -0.66178489  0.0892251   1.19081155  0.68012029 -1.82997569  0.09922659
  0.37172774 -0.32774945  0.33744771 -1.93801747  1.53584419 -0.43836709
  1.28045001  1.75183767  0.75111384 -0.49764369 -2.1878897  -0.79202516
  0.79756519 -0.0471592  -0.67348493  2.14265382 -0.54031351 -0.94957368
 -0.27768705  0.88523042 -1.58695369  1.6374218  -1.50919488  0.35323405
  0.26075651  2.29601338  1.16729327  0.86747288  0.86072341 -0.95838397
 -0.67583085 -1.41388676  0.97732215 -1.08983972  1.77134885 -0.8429015
 -0.40144833 -0.15310144 -0.01417091 -0.12492587 -0.20209453 -0.70837066
  1.39491684  1.75198273 -0.91119517  0.57909259 -0.63112795  0.33450516
 -0.42003067 -1.16331093 -0.58284415 -0.10681039  0.33837199 -0.62621583
  1.75417204 -1.20249441 -1.68976696 -0.14339471  2.10509947 -0.05681839
 -2.48327677 -1.05742044  0.66874986  0.81904409 -1.70756236 -1.11120653
 -0.53830306

In [ ]:
# Ejericio 6
# Calcular la media de un arreglo usando np.sum

arry = np.array([1,2,3,4,10])
media = np.sum(arry)/len(arry) # Lo que hace len es decirme el numero de elementos que tiene el arreglo}
#print(len(arry))

print(media)


4.0


In [ ]:
# Ejercicio7
# Calcular la varianza de un arreglo usando np.sum y np.mean
print("creacion de vianza de un arreglo usando np.sum y n.mean")
arreglo7 = np.array([1,2,3,4,10])
varianza = np.sum((arreglo7-np.mean(arreglo7))**2)/len(arreglo7)
print(varianza)

# La varianza se calcula  como la sumatoria de la diferencia entre el valor original y su media , todo al cuadrado.
# A todo eso lo debemos dividir por la cantidad de elementos menos 1

arreglo7 = np.array([1,2,3,4,10])
varianza = np.sum((arreglo7-np.mean(arreglo7))**2)/(len(arreglo7)-1)

print(varianza)

creacion de vianza de un arreglo usando np.sum y n.mean
10.0
12.5


In [ ]:
# Ejercicio 8
# Crear un array de números aleatorios usando np.random.randn
print("creacion de un array de nuemros aaleatorios ")
arry_aleatorio = np.random.randn(10)
print(arry_aleatorio)


creacion de un array de nuemros aaleatorios 
[-0.84490707 -0.61967252  1.2642154  -0.37714971  0.51218556 -1.54232364
 -0.30352323 -0.1265164   0.58452466  0.64400962]
