<a href="https://colab.research.google.com/github/bmassuco/Ingenias_DS/blob/main/Notebook_5_Entrega_Massuco.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
# Importamos la biblioteca Numpy
import numpy as np

In [ ]:
# Ejericio 1
# Crear un arreglo de ceros de longitud 12
ej1 = np.zeros(12)
print(ej1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Ejercicio 2
# Crea un arrelgo de longitud 10 con ceros en todas las posiciones y un 10 en la posicion numero 5
ej2 = np.zeros(10)
ej2[4] = 10
print(ej2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
# Ejercicio 3
# Crear un arreglo que tenga los números del 10 al 49

ej3 = np.arange(10,50)
print(ej3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Ejercicio 4
# Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
ej4 = np.arange(9).reshape(3,3)
print(ej4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Ejercicio 5
# Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza.

ej5 = np.random.rand(100)
print(ej5)
print()
print("Cálculo de la media:")
media = np.mean(ej5)
print(media)
print()
print("Cálculo de la varianza:")
varianza = np.var(ej5)
print(varianza)

[0.77859071 0.850895   0.94606798 0.68367117 0.86433087 0.30788616
 0.5749044  0.10655277 0.99260511 0.42791511 0.41835135 0.88835695
 0.88281843 0.36173223 0.98139063 0.35224374 0.77980588 0.53147266
 0.7253205  0.10510546 0.88324782 0.15983756 0.34010731 0.68704855
 0.2949433  0.48072216 0.11676421 0.90444753 0.75928338 0.35999915
 0.83683909 0.85902846 0.20481549 0.45042155 0.06769281 0.43850152
 0.69070593 0.38754641 0.74959812 0.19652905 0.7213624  0.96247502
 0.36734189 0.46068267 0.21163677 0.82541908 0.3790102  0.95267195
 0.58345067 0.646257   0.96164566 0.98659614 0.39647094 0.92329167
 0.58889697 0.30966244 0.92293031 0.51842621 0.88702903 0.92282037
 0.20665623 0.21537296 0.97865007 0.22753439 0.32869385 0.63608737
 0.14615491 0.9970913  0.41910001 0.24607026 0.50206356 0.22968218
 0.18508452 0.43052856 0.39542815 0.74103964 0.62422302 0.22605252
 0.41740239 0.6547084  0.1892175  0.8350346  0.31573704 0.7835447
 0.83608101 0.94935021 0.21266163 0.71217633 0.64721504 0.39236

In [ ]:
# Ejericio 6
# Calcular la media de un arreglo usando np.sum

ej6 = np.array([2,4,32,8,11.5,21.3])
media_6 = np.sum(ej6)/len(ej6)
print(f"La media es de {media_6:.2f}")

La media es de 13.13


In [ ]:
# Ejercicio7
# Calcular la varianza de un arreglo usando np.sum y np.mean

ej7 = np.array([11,23.5,32,7.8,9.35,19,24.8])
print("Cálculo de la media:")
media_7 = np.mean(ej7)
print(media_7)
print()
print("Cálculo de la varianza:")
varianza = np.sum((ej7-media_7)**2/len(ej7)-1)
print(varianza)
print(np.var(ej7))

Cálculo de la media:
18.207142857142856

Cálculo de la varianza:
64.57887755102041
71.5788775510204


In [ ]:
# Ejercicio 8
# Crear un array de números aleatorios usando np.random.randn
print("Array de números aleatorios:")
array_random = np.random.randn(15)
print(array_random)


Array de números aleatorios:
[ 0.3280528  -1.4236051  -0.43484666  0.0640904   0.86951333  1.80669584
 -0.1156216   0.92585602  1.35813916  0.44919784  1.38384003 -0.79087238
  0.26452965  0.42413833  0.57499247]
